
AWSTemplateFormatVersion: '2010-09-09'
Description: Role to allow developers to launch instances

Resources:
  ECSTaskRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::123456789101:root
            Action: ['sts:AssumeRole']
            Condition:
              StringLike: 
                aws:PrincipalOrgID: "122345" 
        Path: /
        Policies:
          - PolicyName: AmazonEc2LaunchInstances
            PolicyDocument:
              Statement:
              - Effect: Allow
                Action:
                  - 'ec2:*'
                Resource: '*'
                   
