name: cfn-guard

on: push

jobs: 
  cfn-guard: 
    name: lint-template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install CFN-Guard
        run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
      
      - name: Validate templates
        run: ~/.guard/bin/cfn-guard validate -d ./ -r ./ --show-summary all
